---

name: misc

on:
  push:
    branches: [main]
    paths: ['.github/workflows/misc.yml']
  pull_request:
    branches: [main]
    paths: ['.github/workflows/misc.yml']
  schedule:
    # Everyday
    - cron: '5 13 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - upstream: llvm/llvm-project
            name: llvm-project
            branch: main

    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ./.github/actions/sync/
        with:
          token: ${{ secrets.GH_SECRET_TOKEN }}
          upstream: ${{ matrix.repo.upstream }}
          name: ${{ matrix.repo.name }}
          branch: ${{ matrix.repo.branch }}
